#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;

require_once('vendor/autoload.php');

$application = new Application();
$application->add(new \MoneyMedia\Command\StatusCommand);
$application->add(new \MoneyMedia\Command\MergeCommand);
$application->run();
